export function buildUIGenerationPrompt({ screenshots, markedPositions, goal }) {
  const marksInfo = markedPositions
    .map((m, i) => `  Step ${i + 1}: user marked position (x=${m.x.toFixed(3)}, y=${m.y.toFixed(3)}) on screenshot ${i + 1}`)
    .join('\n');

  const system = [
    "You are an expert mobile UI developer who creates pixel-perfect HTML replicas of app screenshots.",
    "You write clean, production-quality HTML/CSS/JS that faithfully reproduces mobile app interfaces.",
    "You focus on mobile-first design for 375px wide screens at 2x density.",
    "ALL text and labels MUST be in Chinese if the original app uses Chinese.",
    "Return ONLY valid JSON — the HTML must be inside a JSON string field. No markdown fences."
  ].join(" ");

  const user = [
    `I will show you ${screenshots.length} screenshots from a mobile app.`,
    goal ? `The user is building a tutorial to teach an elderly person: ${goal}` : '',
    '',
    'The user has marked positions on each screenshot that represent the buttons',
    'an elderly person needs to click to complete the operation:',
    marksInfo,
    '',
    '=== YOUR TASK ===',
    'Create a COMPLETE standalone HTML page that replicates the app interface shown in the first screenshot.',
    'The HTML page should look and feel like a REAL mobile app screen — not a wireframe, not a list of buttons.',
    'Use the screenshots as visual reference: copy the layout, colors, text, icons, and structure.',
    '',
    '=== REQUIREMENTS ===',
    '1. Mobile-first design: 375px max-width, centered on screen, with phone-frame styling',
    '2. REALISTIC content: Include the actual list items, navigation bars, tab bars, text, avatars,',
    '   switches, dividers — everything visible in the screenshot',
    '3. Accurate colors: Extract hex colors from the screenshot (background, text, accent, buttons)',
    '4. Chinese text: All labels, titles, and button text should match the screenshot',
    '',
    '=== TARGET BUTTONS (CRITICAL) ===',
    'For EACH marked position listed above, create a clearly visible button in the HTML.',
    'Each target button must have:',
    '  - onclick="onTargetClick(stepIndex)" where stepIndex is 1, 2, 3... in order',
    '  - A subtle glow/pulse animation so elderly users can easily spot it',
    '  - The EXACT text/label shown on that button in the screenshot',
    '  - The button\'s real background color extracted from the screenshot',
    '  - Large enough touch target (at least 44x44 CSS pixels)',
    '',
    '=== JAVASCRIPT BRIDGE ===',
    'Include this exact script at the bottom of <body>:',
    '<script>',
    'function onTargetClick(step) {',
    '  // Notify Flutter via the bridge',
    '  if (window.TargetBridge) {',
    '    window.TargetBridge.postMessage(JSON.stringify({event: "target_click", stepIndex: step}));',
    '  }',
    '  // Visual feedback',
    '  const btn = event.target;',
    '  btn.style.transform = "scale(0.92)";',
    '  setTimeout(() => { btn.style.transform = ""; }, 200);',
    '}',
    'function onWrongClick() {',
    '  if (window.TargetBridge) {',
    '    window.TargetBridge.postMessage(JSON.stringify({event: "wrong_click"}));',
    '  }',
    '}',
    '</script>',
    '',
    '=== STYLING ===',
    '- Use system fonts: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    '- Use CSS variables for the color scheme',
    '- Add a phone-frame wrapper with rounded corners and shadow',
    '- Target buttons: add a CSS animation "pulse" (gentle scale 1→1.04→1, 1.5s loop)',
    '- Use Flexbox/Grid for layout',
    '- Include a status bar area at the top',
    '- Bottom tab bar if the screenshot shows one',
    '',
    '=== RETURN FORMAT ===',
    'Return this EXACT JSON (replace the HTML content):',
    '{',
    '  "html": "<!DOCTYPE html>\\n<html>...complete HTML here...</html>",',
    '  "title": "Page title in Chinese",',
    '  "description": "Brief description of what this page shows"',
    '}',
    '',
    'IMPORTANT:',
    '- The "html" string must be a COMPLETE, SELF-CONTAINED HTML document',
    '- All CSS must be inline or in a <style> block (no external files)',
    '- Make the page look REAL — study the screenshot carefully and reproduce it',
    '- Target buttons should blend naturally with the UI (not look out of place)',
    '- The HTML must work standalone — open it in any browser and it should look good'
  ].join('\n');

  return { system, user };
}
